begin;

create table if not exists public.publisher_requests (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.user_profiles(id),
  supersedes_request_id bigint null references public.publisher_requests(id),
  review_status text not null default 'pending_review',
  organizer_type text not null,
  full_name text not null,
  commercial_name text null,
  city_id bigint not null references public.cities(id),
  phone text not null,
  instagram text null,
  website text null,
  activity_description text not null,
  has_physical_location boolean not null default false,
  address_line_1 text null,
  user_feedback_summary text null,
  user_feedback_json jsonb not null default '[]'::jsonb,
  internal_review_notes text null,
  reviewed_by uuid null references public.user_profiles(id),
  reviewed_at timestamptz null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  submitted_at timestamptz not null default now(),
  constraint publisher_requests_review_status_check
    check (review_status in ('pending_review', 'needs_changes', 'approved', 'rejected')),
  constraint publisher_requests_organizer_type_check
    check (organizer_type in ('individual', 'company_or_entity')),
  constraint publisher_requests_feedback_json_array_check
    check (jsonb_typeof(user_feedback_json) = 'array'),
  constraint publisher_requests_company_commercial_name_check
    check (
      organizer_type <> 'company_or_entity'
      or nullif(trim(coalesce(commercial_name, '')), '') is not null
    ),
  constraint publisher_requests_physical_address_check
    check (
      has_physical_location = false
      or nullif(trim(coalesce(address_line_1, '')), '') is not null
    )
);

create table if not exists public.publisher_profiles (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.user_profiles(id),
  publisher_request_id bigint null references public.publisher_requests(id),
  is_active boolean not null default true,
  organizer_type text not null,
  full_name text not null,
  commercial_name text null,
  city_id bigint not null references public.cities(id),
  phone text not null,
  instagram text null,
  website text null,
  activity_description text not null,
  has_physical_location boolean not null default false,
  address_line_1 text null,
  approved_by uuid null references public.user_profiles(id),
  approved_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint publisher_profiles_organizer_type_check
    check (organizer_type in ('individual', 'company_or_entity')),
  constraint publisher_profiles_company_commercial_name_check
    check (
      organizer_type <> 'company_or_entity'
      or nullif(trim(coalesce(commercial_name, '')), '') is not null
    ),
  constraint publisher_profiles_physical_address_check
    check (
      has_physical_location = false
      or nullif(trim(coalesce(address_line_1, '')), '') is not null
    )
);

create index if not exists publisher_requests_user_submitted_idx
  on public.publisher_requests (user_id, submitted_at desc, id desc);

create index if not exists publisher_requests_review_status_idx
  on public.publisher_requests (review_status, submitted_at desc, id desc);

create unique index if not exists publisher_requests_one_pending_per_user_idx
  on public.publisher_requests (user_id)
  where review_status = 'pending_review';

create index if not exists publisher_profiles_user_idx
  on public.publisher_profiles (user_id);

create unique index if not exists publisher_profiles_one_active_per_user_idx
  on public.publisher_profiles (user_id)
  where is_active = true;

alter table public.publisher_requests enable row level security;
alter table public.publisher_profiles enable row level security;

revoke all on table public.publisher_requests from public;
revoke all on table public.publisher_requests from anon;
revoke all on table public.publisher_requests from authenticated;

revoke all on table public.publisher_profiles from public;
revoke all on table public.publisher_profiles from anon;
revoke all on table public.publisher_profiles from authenticated;

-- Read access is RPC-only so internal review notes and reviewer IDs stay private.

drop policy if exists publisher_requests_select_own on public.publisher_requests;
create policy publisher_requests_select_own
  on public.publisher_requests
  for select
  to authenticated
  using (auth.uid() = user_id);

drop policy if exists publisher_profiles_select_own on public.publisher_profiles;
create policy publisher_profiles_select_own
  on public.publisher_profiles
  for select
  to authenticated
  using (auth.uid() = user_id);

create or replace function public.normalize_publisher_request_payload(p_payload jsonb)
returns table (
  full_name text,
  organizer_type text,
  commercial_name text,
  city_id bigint,
  phone text,
  instagram text,
  website text,
  activity_description text,
  has_physical_location boolean,
  address_line_1 text
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  normalized_organizer_type text;
  normalized_city_id bigint;
  normalized_has_physical_location boolean;
  raw_website text;
  normalized_website text;
begin
  if p_payload is null or jsonb_typeof(p_payload) <> 'object' then
    raise exception 'publisher request payload must be a JSON object';
  end if;

  full_name := nullif(trim(coalesce(p_payload ->> 'full_name', '')), '');
  normalized_organizer_type := lower(trim(coalesce(p_payload ->> 'organizer_type', '')));
  commercial_name := nullif(trim(coalesce(p_payload ->> 'commercial_name', '')), '');
  phone := nullif(trim(coalesce(p_payload ->> 'phone', '')), '');
  instagram := nullif(trim(coalesce(p_payload ->> 'instagram', '')), '');
  activity_description := nullif(trim(coalesce(p_payload ->> 'activity_description', '')), '');
  address_line_1 := nullif(trim(coalesce(p_payload ->> 'address_line_1', '')), '');

  normalized_has_physical_location := coalesce(
    nullif(trim(coalesce(p_payload ->> 'has_physical_location', '')), '')::boolean,
    false
  );

  if full_name is null then
    raise exception 'full_name is required';
  end if;

  if normalized_organizer_type not in ('individual', 'company_or_entity') then
    raise exception 'organizer_type is invalid';
  end if;

  organizer_type := normalized_organizer_type;

  if organizer_type = 'company_or_entity' and commercial_name is null then
    raise exception 'commercial_name is required for company_or_entity';
  end if;

  if organizer_type <> 'company_or_entity' then
    normalized_has_physical_location := false;
  end if;

  has_physical_location := normalized_has_physical_location;

  if has_physical_location and address_line_1 is null then
    raise exception 'address_line_1 is required for physical locations';
  end if;

  if not (coalesce(p_payload ->> 'city_id', '') ~ '^\d+$') then
    raise exception 'city_id is required';
  end if;

  normalized_city_id := (p_payload ->> 'city_id')::bigint;

  if not exists (
    select 1
    from public.cities
    where id = normalized_city_id
      and is_active = true
      and place_type = 'municipality'
      and country_code = 'ES'
      and municipality_code is not null
      and dir3_code is not null
  ) then
    raise exception 'city_id must reference an active ES municipality';
  end if;

  city_id := normalized_city_id;

  if phone is null then
    raise exception 'phone is required';
  end if;

  if activity_description is null then
    raise exception 'activity_description is required';
  end if;

  raw_website := nullif(trim(coalesce(p_payload ->> 'website', '')), '');

  if raw_website is null then
    normalized_website := null;
  elsif raw_website !~* '^[a-z][a-z0-9+.-]*://' then
    normalized_website := 'https://' || raw_website;
  else
    normalized_website := raw_website;
  end if;

  if normalized_website is not null and normalized_website !~* '^https?://[^[:space:]]+\.[^[:space:]]+' then
    raise exception 'website must be an http or https URL';
  end if;

  website := normalized_website;

  if instagram is not null and instagram ~ '[[:space:]]' then
    raise exception 'instagram must not contain spaces';
  end if;

  return next;
end;
$$;

create or replace function public.get_my_publisher_status()
returns table (
  status text,
  latest_request_id bigint,
  latest_request jsonb,
  active_profile jsonb,
  can_submit_activities boolean,
  can_request boolean,
  can_resubmit boolean,
  user_feedback_summary text,
  user_feedback_json jsonb
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  latest_request_row public.publisher_requests;
  active_profile_row public.publisher_profiles;
  resolved_status text := 'not_requested';
begin
  if auth.uid() is null then
    raise exception 'auth.uid() is required';
  end if;

  select *
  into latest_request_row
  from public.publisher_requests
  where user_id = auth.uid()
  order by submitted_at desc, id desc
  limit 1;

  select *
  into active_profile_row
  from public.publisher_profiles
  where user_id = auth.uid()
    and is_active = true
  order by approved_at desc, id desc
  limit 1;

  if active_profile_row.id is not null then
    resolved_status := 'approved';
  elsif latest_request_row.id is not null then
    resolved_status := latest_request_row.review_status;
  end if;

  return query
  select
    resolved_status::text,
    latest_request_row.id::bigint,
    case
      when latest_request_row.id is null then null::jsonb
      else jsonb_strip_nulls(jsonb_build_object(
        'id', latest_request_row.id,
        'status', latest_request_row.review_status,
        'organizer_type', latest_request_row.organizer_type,
        'full_name', latest_request_row.full_name,
        'commercial_name', latest_request_row.commercial_name,
        'city_id', latest_request_row.city_id,
        'phone', latest_request_row.phone,
        'instagram', latest_request_row.instagram,
        'website', latest_request_row.website,
        'activity_description', latest_request_row.activity_description,
        'has_physical_location', latest_request_row.has_physical_location,
        'address_line_1', latest_request_row.address_line_1,
        'user_feedback_summary', latest_request_row.user_feedback_summary,
        'user_feedback_json', latest_request_row.user_feedback_json,
        'reviewed_at', latest_request_row.reviewed_at,
        'submitted_at', latest_request_row.submitted_at,
        'updated_at', latest_request_row.updated_at
      ))
    end,
    case
      when active_profile_row.id is null then null::jsonb
      else jsonb_strip_nulls(jsonb_build_object(
        'id', active_profile_row.id,
        'organizer_type', active_profile_row.organizer_type,
        'full_name', active_profile_row.full_name,
        'commercial_name', active_profile_row.commercial_name,
        'city_id', active_profile_row.city_id,
        'phone', active_profile_row.phone,
        'instagram', active_profile_row.instagram,
        'website', active_profile_row.website,
        'activity_description', active_profile_row.activity_description,
        'has_physical_location', active_profile_row.has_physical_location,
        'address_line_1', active_profile_row.address_line_1,
        'approved_at', active_profile_row.approved_at
      ))
    end,
    (active_profile_row.id is not null and active_profile_row.is_active = true)::boolean,
    (resolved_status in ('not_requested', 'rejected'))::boolean,
    (latest_request_row.id is not null and resolved_status in ('needs_changes', 'rejected'))::boolean,
    latest_request_row.user_feedback_summary::text,
    coalesce(latest_request_row.user_feedback_json, '[]'::jsonb)::jsonb;
end;
$$;

create or replace function public.submit_my_publisher_request(p_payload jsonb)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  normalized_payload record;
  latest_request_row public.publisher_requests;
  new_request_id bigint;
begin
  if auth.uid() is null then
    raise exception 'auth.uid() is required';
  end if;

  if exists (
    select 1
    from public.publisher_profiles
    where user_id = auth.uid()
      and is_active = true
  ) then
    raise exception 'publisher profile is already approved';
  end if;

  select *
  into latest_request_row
  from public.publisher_requests
  where user_id = auth.uid()
  order by submitted_at desc, id desc
  limit 1;

  if latest_request_row.review_status in ('pending_review', 'needs_changes', 'approved') then
    raise exception 'publisher request cannot be submitted in current status';
  end if;

  select *
  into normalized_payload
  from public.normalize_publisher_request_payload(p_payload);

  insert into public.publisher_requests (
    user_id,
    supersedes_request_id,
    review_status,
    organizer_type,
    full_name,
    commercial_name,
    city_id,
    phone,
    instagram,
    website,
    activity_description,
    has_physical_location,
    address_line_1
  )
  values (
    auth.uid(),
    case when latest_request_row.review_status = 'rejected' then latest_request_row.id else null end,
    'pending_review',
    normalized_payload.organizer_type,
    normalized_payload.full_name,
    normalized_payload.commercial_name,
    normalized_payload.city_id,
    normalized_payload.phone,
    normalized_payload.instagram,
    normalized_payload.website,
    normalized_payload.activity_description,
    normalized_payload.has_physical_location,
    normalized_payload.address_line_1
  )
  returning id into new_request_id;

  return new_request_id;
end;
$$;

create or replace function public.resubmit_my_publisher_request(
  p_request_id bigint,
  p_payload jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  previous_request_row public.publisher_requests;
  normalized_payload record;
  new_request_id bigint;
begin
  if auth.uid() is null then
    raise exception 'auth.uid() is required';
  end if;

  select *
  into previous_request_row
  from public.publisher_requests
  where id = p_request_id
    and user_id = auth.uid()
  limit 1;

  if previous_request_row.id is null then
    raise exception 'publisher request is not available for current user';
  end if;

  if previous_request_row.review_status not in ('needs_changes', 'rejected') then
    raise exception 'publisher request is not available for resubmission';
  end if;

  if exists (
    select 1
    from public.publisher_profiles
    where user_id = auth.uid()
      and is_active = true
  ) then
    raise exception 'publisher profile is already approved';
  end if;

  if exists (
    select 1
    from public.publisher_requests
    where user_id = auth.uid()
      and review_status = 'pending_review'
  ) then
    raise exception 'publisher request is already pending review';
  end if;

  select *
  into normalized_payload
  from public.normalize_publisher_request_payload(p_payload);

  insert into public.publisher_requests (
    user_id,
    supersedes_request_id,
    review_status,
    organizer_type,
    full_name,
    commercial_name,
    city_id,
    phone,
    instagram,
    website,
    activity_description,
    has_physical_location,
    address_line_1
  )
  values (
    auth.uid(),
    previous_request_row.id,
    'pending_review',
    normalized_payload.organizer_type,
    normalized_payload.full_name,
    normalized_payload.commercial_name,
    normalized_payload.city_id,
    normalized_payload.phone,
    normalized_payload.instagram,
    normalized_payload.website,
    normalized_payload.activity_description,
    normalized_payload.has_physical_location,
    normalized_payload.address_line_1
  )
  returning id into new_request_id;

  return new_request_id;
end;
$$;

create or replace function public.list_internal_publisher_requests(p_status text default null)
returns table (
  request_id bigint,
  user_email text,
  full_name text,
  organizer_type text,
  commercial_name text,
  city_id bigint,
  city_name text,
  phone text,
  instagram text,
  website text,
  activity_description text,
  has_physical_location boolean,
  address_line_1 text,
  review_status text,
  user_feedback_summary text,
  user_feedback_json jsonb,
  internal_review_notes text,
  reviewed_at timestamptz,
  submitted_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  normalized_status text := nullif(trim(coalesce(p_status, '')), '');
begin
  if auth.uid() is null then
    raise exception 'auth.uid() is required';
  end if;

  if not exists (
    select 1
    from public.internal_tool_access
    where user_id = auth.uid()
      and tool_name = 'draft_inbox'
  ) then
    raise exception 'draft_inbox access is required';
  end if;

  if normalized_status = 'all' then
    normalized_status := null;
  end if;

  if normalized_status is not null
    and normalized_status not in ('pending_review', 'needs_changes', 'approved', 'rejected') then
    raise exception 'publisher request status filter is invalid';
  end if;

  return query
  select
    publisher_requests.id::bigint,
    user_profiles.email::text,
    publisher_requests.full_name::text,
    publisher_requests.organizer_type::text,
    publisher_requests.commercial_name::text,
    publisher_requests.city_id::bigint,
    cities.name::text,
    publisher_requests.phone::text,
    publisher_requests.instagram::text,
    publisher_requests.website::text,
    publisher_requests.activity_description::text,
    publisher_requests.has_physical_location::boolean,
    publisher_requests.address_line_1::text,
    publisher_requests.review_status::text,
    publisher_requests.user_feedback_summary::text,
    publisher_requests.user_feedback_json::jsonb,
    publisher_requests.internal_review_notes::text,
    publisher_requests.reviewed_at::timestamptz,
    publisher_requests.submitted_at::timestamptz,
    publisher_requests.created_at::timestamptz,
    publisher_requests.updated_at::timestamptz
  from public.publisher_requests
  left join public.user_profiles
    on user_profiles.id = publisher_requests.user_id
  left join public.cities
    on cities.id = publisher_requests.city_id
  where normalized_status is null
    or publisher_requests.review_status = normalized_status
  order by publisher_requests.submitted_at desc, publisher_requests.id desc;
end;
$$;

create or replace function public.get_internal_publisher_request(p_request_id bigint)
returns table (
  request_id bigint,
  user_email text,
  full_name text,
  organizer_type text,
  commercial_name text,
  city_id bigint,
  city_name text,
  phone text,
  instagram text,
  website text,
  activity_description text,
  has_physical_location boolean,
  address_line_1 text,
  review_status text,
  user_feedback_summary text,
  user_feedback_json jsonb,
  internal_review_notes text,
  reviewed_at timestamptz,
  submitted_at timestamptz,
  created_at timestamptz,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  return query
  select *
  from public.list_internal_publisher_requests(null) as requests
  where requests.request_id = p_request_id
  limit 1;
end;
$$;

create or replace function public.request_internal_publisher_changes(
  p_request_id bigint,
  p_user_feedback_summary text,
  p_user_feedback_json jsonb default '[]'::jsonb,
  p_internal_review_notes text default null
)
returns table (
  request_id bigint,
  review_status text,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if auth.uid() is null then
    raise exception 'auth.uid() is required';
  end if;

  if not exists (
    select 1
    from public.internal_tool_access
    where user_id = auth.uid()
      and tool_name = 'draft_inbox'
  ) then
    raise exception 'draft_inbox access is required';
  end if;

  if nullif(trim(coalesce(p_user_feedback_summary, '')), '') is null then
    raise exception 'user feedback summary is required';
  end if;

  if p_user_feedback_json is null or jsonb_typeof(p_user_feedback_json) <> 'array' then
    raise exception 'user feedback must be a JSON array';
  end if;

  return query
  update public.publisher_requests as requests
  set
    review_status = 'needs_changes',
    user_feedback_summary = trim(p_user_feedback_summary),
    user_feedback_json = p_user_feedback_json,
    internal_review_notes = nullif(trim(coalesce(p_internal_review_notes, '')), ''),
    reviewed_by = auth.uid(),
    reviewed_at = now(),
    updated_at = now()
  where requests.id = p_request_id
    and requests.review_status = 'pending_review'
  returning
    requests.id::bigint,
    requests.review_status::text,
    requests.updated_at::timestamptz;
end;
$$;

create or replace function public.reject_internal_publisher_request(
  p_request_id bigint,
  p_user_feedback_summary text,
  p_user_feedback_json jsonb default '[]'::jsonb,
  p_internal_review_notes text default null
)
returns table (
  request_id bigint,
  review_status text,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if auth.uid() is null then
    raise exception 'auth.uid() is required';
  end if;

  if not exists (
    select 1
    from public.internal_tool_access
    where user_id = auth.uid()
      and tool_name = 'draft_inbox'
  ) then
    raise exception 'draft_inbox access is required';
  end if;

  if nullif(trim(coalesce(p_user_feedback_summary, '')), '') is null then
    raise exception 'user feedback summary is required';
  end if;

  if p_user_feedback_json is null or jsonb_typeof(p_user_feedback_json) <> 'array' then
    raise exception 'user feedback must be a JSON array';
  end if;

  return query
  update public.publisher_requests as requests
  set
    review_status = 'rejected',
    user_feedback_summary = trim(p_user_feedback_summary),
    user_feedback_json = p_user_feedback_json,
    internal_review_notes = nullif(trim(coalesce(p_internal_review_notes, '')), ''),
    reviewed_by = auth.uid(),
    reviewed_at = now(),
    updated_at = now()
  where requests.id = p_request_id
    and requests.review_status = 'pending_review'
  returning
    requests.id::bigint,
    requests.review_status::text,
    requests.updated_at::timestamptz;
end;
$$;

create or replace function public.approve_internal_publisher_request(
  p_request_id bigint,
  p_internal_review_notes text default null
)
returns table (
  request_id bigint,
  profile_id bigint,
  review_status text,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  request_row public.publisher_requests;
  active_profile_id bigint;
begin
  if auth.uid() is null then
    raise exception 'auth.uid() is required';
  end if;

  if not exists (
    select 1
    from public.internal_tool_access
    where user_id = auth.uid()
      and tool_name = 'draft_inbox'
  ) then
    raise exception 'draft_inbox access is required';
  end if;

  select requests.*
  into request_row
  from public.publisher_requests as requests
  where requests.id = p_request_id
    and requests.review_status = 'pending_review'
  for update;

  if request_row.id is null then
    raise exception 'publisher request is not pending review';
  end if;

  select profiles.id
  into active_profile_id
  from public.publisher_profiles as profiles
  where profiles.user_id = request_row.user_id
    and profiles.is_active = true
  order by profiles.approved_at desc, profiles.id desc
  limit 1;

  if active_profile_id is null then
    insert into public.publisher_profiles (
      user_id,
      publisher_request_id,
      is_active,
      organizer_type,
      full_name,
      commercial_name,
      city_id,
      phone,
      instagram,
      website,
      activity_description,
      has_physical_location,
      address_line_1,
      approved_by
    )
    values (
      request_row.user_id,
      request_row.id,
      true,
      request_row.organizer_type,
      request_row.full_name,
      request_row.commercial_name,
      request_row.city_id,
      request_row.phone,
      request_row.instagram,
      request_row.website,
      request_row.activity_description,
      request_row.has_physical_location,
      request_row.address_line_1,
      auth.uid()
    )
    returning id into active_profile_id;
  else
    update public.publisher_profiles as profiles
    set
      publisher_request_id = request_row.id,
      is_active = true,
      organizer_type = request_row.organizer_type,
      full_name = request_row.full_name,
      commercial_name = request_row.commercial_name,
      city_id = request_row.city_id,
      phone = request_row.phone,
      instagram = request_row.instagram,
      website = request_row.website,
      activity_description = request_row.activity_description,
      has_physical_location = request_row.has_physical_location,
      address_line_1 = request_row.address_line_1,
      approved_by = auth.uid(),
      approved_at = now(),
      updated_at = now()
    where profiles.id = active_profile_id;
  end if;

  update public.publisher_requests as requests
  set
    review_status = 'approved',
    user_feedback_summary = null,
    user_feedback_json = '[]'::jsonb,
    internal_review_notes = nullif(trim(coalesce(p_internal_review_notes, '')), ''),
    reviewed_by = auth.uid(),
    reviewed_at = now(),
    updated_at = now()
  where requests.id = request_row.id
  returning
    requests.id,
    requests.review_status,
    requests.updated_at
  into request_row.id, request_row.review_status, request_row.updated_at;

  return query
  select
    request_row.id::bigint,
    active_profile_id::bigint,
    request_row.review_status::text,
    request_row.updated_at::timestamptz;
end;
$$;

create or replace function public.enforce_approved_publisher_for_activity_submission()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  resolved_user_id uuid := coalesce(new.submitted_by_user_id, auth.uid());
begin
  if new.source_type = 'user_submission'
    and new.parent_draft_id is null
    and new.edit_activity_id is null
    and coalesce(new.revision_number, 1) = 1 then
    if resolved_user_id is null then
      raise exception 'auth.uid() is required';
    end if;

    if not exists (
      select 1
      from public.publisher_profiles
      where user_id = resolved_user_id
        and is_active = true
    ) then
      raise exception 'approved publisher status is required to submit new activities';
    end if;
  end if;

  return new;
end;
$$;

drop trigger if exists activity_drafts_require_approved_publisher_for_submission
  on public.activity_drafts;

create trigger activity_drafts_require_approved_publisher_for_submission
  before insert on public.activity_drafts
  for each row
  execute function public.enforce_approved_publisher_for_activity_submission();

revoke all on function public.normalize_publisher_request_payload(jsonb) from public;
revoke all on function public.normalize_publisher_request_payload(jsonb) from anon;
revoke all on function public.normalize_publisher_request_payload(jsonb) from authenticated;

revoke all on function public.get_my_publisher_status() from public;
revoke all on function public.get_my_publisher_status() from anon;
revoke all on function public.get_my_publisher_status() from authenticated;
grant execute on function public.get_my_publisher_status() to authenticated;

revoke all on function public.submit_my_publisher_request(jsonb) from public;
revoke all on function public.submit_my_publisher_request(jsonb) from anon;
revoke all on function public.submit_my_publisher_request(jsonb) from authenticated;
grant execute on function public.submit_my_publisher_request(jsonb) to authenticated;

revoke all on function public.resubmit_my_publisher_request(bigint, jsonb) from public;
revoke all on function public.resubmit_my_publisher_request(bigint, jsonb) from anon;
revoke all on function public.resubmit_my_publisher_request(bigint, jsonb) from authenticated;
grant execute on function public.resubmit_my_publisher_request(bigint, jsonb) to authenticated;

revoke all on function public.list_internal_publisher_requests(text) from public;
revoke all on function public.list_internal_publisher_requests(text) from anon;
revoke all on function public.list_internal_publisher_requests(text) from authenticated;
grant execute on function public.list_internal_publisher_requests(text) to authenticated;

revoke all on function public.get_internal_publisher_request(bigint) from public;
revoke all on function public.get_internal_publisher_request(bigint) from anon;
revoke all on function public.get_internal_publisher_request(bigint) from authenticated;
grant execute on function public.get_internal_publisher_request(bigint) to authenticated;

revoke all on function public.request_internal_publisher_changes(bigint, text, jsonb, text) from public;
revoke all on function public.request_internal_publisher_changes(bigint, text, jsonb, text) from anon;
revoke all on function public.request_internal_publisher_changes(bigint, text, jsonb, text) from authenticated;
grant execute on function public.request_internal_publisher_changes(bigint, text, jsonb, text) to authenticated;

revoke all on function public.reject_internal_publisher_request(bigint, text, jsonb, text) from public;
revoke all on function public.reject_internal_publisher_request(bigint, text, jsonb, text) from anon;
revoke all on function public.reject_internal_publisher_request(bigint, text, jsonb, text) from authenticated;
grant execute on function public.reject_internal_publisher_request(bigint, text, jsonb, text) to authenticated;

revoke all on function public.approve_internal_publisher_request(bigint, text) from public;
revoke all on function public.approve_internal_publisher_request(bigint, text) from anon;
revoke all on function public.approve_internal_publisher_request(bigint, text) from authenticated;
grant execute on function public.approve_internal_publisher_request(bigint, text) to authenticated;

revoke all on function public.enforce_approved_publisher_for_activity_submission() from public;
revoke all on function public.enforce_approved_publisher_for_activity_submission() from anon;
revoke all on function public.enforce_approved_publisher_for_activity_submission() from authenticated;

comment on table public.publisher_requests is
  'Lifecycle and audit table for normal users requesting approved publisher/Organizador capability.';

comment on table public.publisher_profiles is
  'Active approved publisher state used to gate new activity submissions. Not public profile data in v1.';

comment on function public.get_my_publisher_status() is
  'Returns the current authenticated user publisher request status, safe request/profile fields, and submission capability.';

comment on function public.submit_my_publisher_request(jsonb) is
  'Creates a pending publisher request for the authenticated user. It does not create a publisher profile or publication rights.';

comment on function public.resubmit_my_publisher_request(bigint, jsonb) is
  'Creates a new pending publisher request linked to a needs_changes or rejected request owned by the authenticated user.';

comment on function public.approve_internal_publisher_request(bigint, text) is
  'Approves a publisher request for internal Draft Inbox reviewers and creates or updates the active publisher profile.';

comment on function public.create_my_activity_submission(jsonb, text) is
  'Creates a pending_review activity_draft for an authenticated approved publisher submission. Approval is enforced by activity_drafts_require_approved_publisher_for_submission.';

notify pgrst, 'reload schema';

commit;
