-- Generated by scripts/generate-dir3-municipalities.mjs.
-- Source: official DIR3 Catalogo de Localidades, municipality rows only (Cod. Entidad = 01).
-- Row count: 131
-- Chunk: 9 of 9

begin;

create temp table dir3_municipality_seed (
  dir3_code text primary key,
  municipality_code text not null,
  name text not null,
  name_search text not null,
  slug text not null,
  province_code text not null,
  province_name text not null,
  autonomous_community_code text not null,
  autonomous_community_name text not null,
  country_code text not null,
  source_name text not null,
  source_file text not null,
  source_downloaded_at date not null,
  search_text text not null
) on commit drop;

insert into dir3_municipality_seed (
  dir3_code,
  municipality_code,
  name,
  name_search,
  slug,
  province_code,
  province_name,
  autonomous_community_code,
  autonomous_community_name,
  country_code,
  source_name,
  source_file,
  source_downloaded_at,
  search_text
)
values
('L01260488', '260488', 'Cidamón', 'cidamon', 'cidamon', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'cidamon cidamon rioja la la rioja 260488 l01260488'),
('L01260491', '260491', 'Cihuri', 'cihuri', 'cihuri', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'cihuri cihuri rioja la la rioja 260491 l01260491'),
('L01260504', '260504', 'Cirueña', 'ciruena', 'ciruena', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'ciruena ciruena rioja la la rioja 260504 l01260504'),
('L01260511', '260511', 'Clavijo', 'clavijo', 'clavijo', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'clavijo clavijo rioja la la rioja 260511 l01260511'),
('L01260526', '260526', 'Cordovín', 'cordovin', 'cordovin', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'cordovin cordovin rioja la la rioja 260526 l01260526'),
('L01260532', '260532', 'Corera', 'corera', 'corera', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'corera corera rioja la la rioja 260532 l01260532'),
('L01260547', '260547', 'Cornago', 'cornago', 'cornago', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'cornago cornago rioja la la rioja 260547 l01260547'),
('L01260550', '260550', 'Corporales', 'corporales', 'corporales', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'corporales corporales rioja la la rioja 260550 l01260550'),
('L01260563', '260563', 'Cuzcurrita de Río Tirón', 'cuzcurrita de rio tiron', 'cuzcurrita-de-rio-tiron', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'cuzcurrita de rio tiron cuzcurrita de rio tiron rioja la la rioja 260563 l01260563'),
('L01260414', '260414', 'Cárdenas', 'cardenas', 'cardenas', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'cardenas cardenas rioja la la rioja 260414 l01260414'),
('L01260579', '260579', 'Daroca de Rioja', 'daroca de rioja', 'daroca-de-rioja', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'daroca de rioja daroca de rioja rioja la la rioja 260579 l01260579'),
('L01260585', '260585', 'Enciso', 'enciso', 'enciso', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'enciso enciso rioja la la rioja 260585 l01260585'),
('L01260598', '260598', 'Entrena', 'entrena', 'entrena', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'entrena entrena rioja la la rioja 260598 l01260598'),
('L01260602', '260602', 'Estollo', 'estollo', 'estollo', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'estollo estollo rioja la la rioja 260602 l01260602'),
('L01260619', '260619', 'Ezcaray', 'ezcaray', 'ezcaray', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'ezcaray ezcaray rioja la la rioja 260619 l01260619'),
('L01260624', '260624', 'Foncea', 'foncea', 'foncea', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'foncea foncea rioja la la rioja 260624 l01260624'),
('L01260630', '260630', 'Fonzaleche', 'fonzaleche', 'fonzaleche', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'fonzaleche fonzaleche rioja la la rioja 260630 l01260630'),
('L01260645', '260645', 'Fuenmayor', 'fuenmayor', 'fuenmayor', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'fuenmayor fuenmayor rioja la la rioja 260645 l01260645'),
('L01260658', '260658', 'Galbárruli', 'galbarruli', 'galbarruli', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'galbarruli galbarruli rioja la la rioja 260658 l01260658'),
('L01260661', '260661', 'Galilea', 'galilea', 'galilea', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'galilea galilea rioja la la rioja 260661 l01260661'),
('L01260677', '260677', 'Gallinero de Cameros', 'gallinero de cameros', 'gallinero-de-cameros', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'gallinero de cameros gallinero de cameros rioja la la rioja 260677 l01260677'),
('L01260683', '260683', 'Gimileo', 'gimileo', 'gimileo', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'gimileo gimileo rioja la la rioja 260683 l01260683'),
('L01260696', '260696', 'Grañón', 'granon', 'granon', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'granon granon rioja la la rioja 260696 l01260696'),
('L01260700', '260700', 'Grávalos', 'gravalos', 'gravalos', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'gravalos gravalos rioja la la rioja 260700 l01260700'),
('L01260717', '260717', 'Haro', 'haro', 'haro', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'haro haro rioja la la rioja 260717 l01260717'),
('L01260722', '260722', 'Herce', 'herce', 'herce', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'herce herce rioja la la rioja 260722 l01260722'),
('L01260738', '260738', 'Herramélluri', 'herramelluri', 'herramelluri', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'herramelluri herramelluri rioja la la rioja 260738 l01260738'),
('L01260743', '260743', 'Hervías', 'hervias', 'hervias', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'hervias hervias rioja la la rioja 260743 l01260743'),
('L01260756', '260756', 'Hormilla', 'hormilla', 'hormilla', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'hormilla hormilla rioja la la rioja 260756 l01260756'),
('L01260769', '260769', 'Hormilleja', 'hormilleja', 'hormilleja', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'hormilleja hormilleja rioja la la rioja 260769 l01260769'),
('L01260775', '260775', 'Hornillos de Cameros', 'hornillos de cameros', 'hornillos-de-cameros', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'hornillos de cameros hornillos de cameros rioja la la rioja 260775 l01260775'),
('L01260781', '260781', 'Hornos de Moncalvillo', 'hornos de moncalvillo', 'hornos-de-moncalvillo', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'hornos de moncalvillo hornos de moncalvillo rioja la la rioja 260781 l01260781'),
('L01260794', '260794', 'Huércanos', 'huercanos', 'huercanos', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'huercanos huercanos rioja la la rioja 260794 l01260794'),
('L01260808', '260808', 'Igea', 'igea', 'igea', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'igea igea rioja la la rioja 260808 l01260808'),
('L01260815', '260815', 'Jalón de Cameros', 'jalon de cameros', 'jalon-de-cameros', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'jalon de cameros jalon de cameros rioja la la rioja 260815 l01260815'),
('L01260820', '260820', 'Laguna de Cameros', 'laguna de cameros', 'laguna-de-cameros', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'laguna de cameros laguna de cameros rioja la la rioja 260820 l01260820'),
('L01260836', '260836', 'Lagunilla del Jubera', 'lagunilla del jubera', 'lagunilla-del-jubera', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'lagunilla del jubera lagunilla del jubera rioja la la rioja 260836 l01260836'),
('L01260841', '260841', 'Lardero', 'lardero', 'lardero', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'lardero lardero rioja la la rioja 260841 l01260841'),
('L01260867', '260867', 'Ledesma de la Cogolla', 'ledesma de la cogolla', 'ledesma-de-la-cogolla', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'ledesma de la cogolla ledesma de la cogolla rioja la la rioja 260867 l01260867'),
('L01260873', '260873', 'Leiva', 'leiva', 'leiva', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'leiva leiva rioja la la rioja 260873 l01260873'),
('L01260889', '260889', 'Leza de Río Leza', 'leza de rio leza', 'leza-de-rio-leza', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'leza de rio leza leza de rio leza rioja la la rioja 260889 l01260889'),
('L01260892', '260892', 'Logroño', 'logrono', 'logrono', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'logrono logrono rioja la la rioja 260892 l01260892'),
('L01260913', '260913', 'Lumbreras', 'lumbreras', 'lumbreras', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'lumbreras lumbreras rioja la la rioja 260913 l01260913'),
('L01260928', '260928', 'Manjarrés', 'manjarres', 'manjarres', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'manjarres manjarres rioja la la rioja 260928 l01260928'),
('L01260934', '260934', 'Mansilla de la Sierra', 'mansilla de la sierra', 'mansilla-de-la-sierra', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'mansilla de la sierra mansilla de la sierra rioja la la rioja 260934 l01260934'),
('L01260949', '260949', 'Manzanares de Rioja', 'manzanares de rioja', 'manzanares-de-rioja', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'manzanares de rioja manzanares de rioja rioja la la rioja 260949 l01260949'),
('L01260952', '260952', 'Matute', 'matute', 'matute', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'matute matute rioja la la rioja 260952 l01260952'),
('L01260965', '260965', 'Medrano', 'medrano', 'medrano', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'medrano medrano rioja la la rioja 260965 l01260965'),
('L01260987', '260987', 'Munilla', 'munilla', 'munilla', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'munilla munilla rioja la la rioja 260987 l01260987'),
('L01260990', '260990', 'Murillo de Río Leza', 'murillo de rio leza', 'murillo-de-rio-leza', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'murillo de rio leza murillo de rio leza rioja la la rioja 260990 l01260990'),
('L01261004', '261004', 'Muro de Aguas', 'muro de aguas', 'muro-de-aguas', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'muro de aguas muro de aguas rioja la la rioja 261004 l01261004'),
('L01261011', '261011', 'Muro en Cameros', 'muro en cameros', 'muro-en-cameros', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'muro en cameros muro en cameros rioja la la rioja 261011 l01261011'),
('L01261032', '261032', 'Nalda', 'nalda', 'nalda', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'nalda nalda rioja la la rioja 261032 l01261032'),
('L01261047', '261047', 'Navajún', 'navajun', 'navajun', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'navajun navajun rioja la la rioja 261047 l01261047'),
('L01261050', '261050', 'Navarrete', 'navarrete', 'navarrete', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'navarrete navarrete rioja la la rioja 261050 l01261050'),
('L01261063', '261063', 'Nestares', 'nestares', 'nestares', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'nestares nestares rioja la la rioja 261063 l01261063'),
('L01261079', '261079', 'Nieva de Cameros', 'nieva de cameros', 'nieva-de-cameros', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'nieva de cameros nieva de cameros rioja la la rioja 261079 l01261079'),
('L01261026', '261026', 'Nájera', 'najera', 'najera', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'najera najera rioja la la rioja 261026 l01261026'),
('L01261098', '261098', 'Ochánduri', 'ochanduri', 'ochanduri', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'ochanduri ochanduri rioja la la rioja 261098 l01261098'),
('L01261085', '261085', 'Ocón', 'ocon', 'ocon', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'ocon ocon rioja la la rioja 261085 l01261085'),
('L01261102', '261102', 'Ojacastro', 'ojacastro', 'ojacastro', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'ojacastro ojacastro rioja la la rioja 261102 l01261102'),
('L01261119', '261119', 'Ollauri', 'ollauri', 'ollauri', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'ollauri ollauri rioja la la rioja 261119 l01261119'),
('L01261124', '261124', 'Ortigosa de Cameros', 'ortigosa de cameros', 'ortigosa-de-cameros', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'ortigosa de cameros ortigosa de cameros rioja la la rioja 261124 l01261124'),
('L01261130', '261130', 'Pazuengos', 'pazuengos', 'pazuengos', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'pazuengos pazuengos rioja la la rioja 261130 l01261130'),
('L01261145', '261145', 'Pedroso', 'pedroso', 'pedroso', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'pedroso pedroso rioja la la rioja 261145 l01261145'),
('L01261158', '261158', 'Pinillos', 'pinillos', 'pinillos', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'pinillos pinillos rioja la la rioja 261158 l01261158'),
('L01261177', '261177', 'Pradejón', 'pradejon', 'pradejon', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'pradejon pradejon rioja la la rioja 261177 l01261177'),
('L01261183', '261183', 'Pradillo', 'pradillo', 'pradillo', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'pradillo pradillo rioja la la rioja 261183 l01261183'),
('L01261196', '261196', 'Préjano', 'prejano', 'prejano', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'prejano prejano rioja la la rioja 261196 l01261196'),
('L01261200', '261200', 'Quel', 'quel', 'quel', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'quel quel rioja la la rioja 261200 l01261200'),
('L01261217', '261217', 'Rabanera', 'rabanera', 'rabanera', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'rabanera rabanera rioja la la rioja 261217 l01261217'),
('L01261222', '261222', 'Rasillo de Cameros, El', 'rasillo de cameros, el', 'rasillo-de-cameros-el', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'rasillo de cameros el rasillo de cameros el rioja la la rioja 261222 l01261222'),
('L01261238', '261238', 'Redal, El', 'redal, el', 'redal-el', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'redal el redal el rioja la la rioja 261238 l01261238'),
('L01261243', '261243', 'Ribafrecha', 'ribafrecha', 'ribafrecha', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'ribafrecha ribafrecha rioja la la rioja 261243 l01261243'),
('L01261256', '261256', 'Rincón de Soto', 'rincon de soto', 'rincon-de-soto', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'rincon de soto rincon de soto rioja la la rioja 261256 l01261256'),
('L01261269', '261269', 'Robres del Castillo', 'robres del castillo', 'robres-del-castillo', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'robres del castillo robres del castillo rioja la la rioja 261269 l01261269'),
('L01261275', '261275', 'Rodezno', 'rodezno', 'rodezno', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'rodezno rodezno rioja la la rioja 261275 l01261275'),
('L01261281', '261281', 'Sajazarra', 'sajazarra', 'sajazarra', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'sajazarra sajazarra rioja la la rioja 261281 l01261281'),
('L01261294', '261294', 'San Asensio', 'san asensio', 'san-asensio', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'san asensio san asensio rioja la la rioja 261294 l01261294'),
('L01261315', '261315', 'San Millán de Yécora', 'san millan de yecora', 'san-millan-de-yecora', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'san millan de yecora san millan de yecora rioja la la rioja 261315 l01261315'),
('L01261308', '261308', 'San Millán de la Cogolla', 'san millan de la cogolla', 'san-millan-de-la-cogolla', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'san millan de la cogolla san millan de la cogolla rioja la la rioja 261308 l01261308'),
('L01261320', '261320', 'San Román de Cameros', 'san roman de cameros', 'san-roman-de-cameros', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'san roman de cameros san roman de cameros rioja la la rioja 261320 l01261320'),
('L01261392', '261392', 'San Torcuato', 'san torcuato', 'san-torcuato', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'san torcuato san torcuato rioja la la rioja 261392 l01261392'),
('L01261428', '261428', 'San Vicente de la Sonsierra', 'san vicente de la sonsierra', 'san-vicente-de-la-sonsierra', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'san vicente de la sonsierra san vicente de la sonsierra rioja la la rioja 261428 l01261428'),
('L01261341', '261341', 'Santa Coloma', 'santa coloma', 'santa-coloma', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'santa coloma santa coloma rioja la la rioja 261341 l01261341'),
('L01261354', '261354', 'Santa Engracia del Jubera', 'santa engracia del jubera', 'santa-engracia-del-jubera', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'santa engracia del jubera santa engracia del jubera rioja la la rioja 261354 l01261354'),
('L01261367', '261367', 'Santa Eulalia Bajera', 'santa eulalia bajera', 'santa-eulalia-bajera', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'santa eulalia bajera santa eulalia bajera rioja la la rioja 261367 l01261367'),
('L01261389', '261389', 'Santo Domingo de la Calzada', 'santo domingo de la calzada', 'santo-domingo-de-la-calzada', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'santo domingo de la calzada santo domingo de la calzada rioja la la rioja 261389 l01261389'),
('L01261406', '261406', 'Santurde de Rioja', 'santurde de rioja', 'santurde-de-rioja', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'santurde de rioja santurde de rioja rioja la la rioja 261406 l01261406'),
('L01261413', '261413', 'Santurdejo', 'santurdejo', 'santurdejo', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'santurdejo santurdejo rioja la la rioja 261413 l01261413'),
('L01261434', '261434', 'Sojuela', 'sojuela', 'sojuela', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'sojuela sojuela rioja la la rioja 261434 l01261434'),
('L01261449', '261449', 'Sorzano', 'sorzano', 'sorzano', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'sorzano sorzano rioja la la rioja 261449 l01261449'),
('L01261465', '261465', 'Soto en Cameros', 'soto en cameros', 'soto-en-cameros', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'soto en cameros soto en cameros rioja la la rioja 261465 l01261465'),
('L01261452', '261452', 'Sotés', 'sotes', 'sotes', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'sotes sotes rioja la la rioja 261452 l01261452'),
('L01261471', '261471', 'Terroba', 'terroba', 'terroba', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'terroba terroba rioja la la rioja 261471 l01261471'),
('L01261487', '261487', 'Tirgo', 'tirgo', 'tirgo', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'tirgo tirgo rioja la la rioja 261487 l01261487'),
('L01261490', '261490', 'Tobía', 'tobia', 'tobia', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'tobia tobia rioja la la rioja 261490 l01261490'),
('L01261503', '261503', 'Tormantos', 'tormantos', 'tormantos', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'tormantos tormantos rioja la la rioja 261503 l01261503'),
('L01261531', '261531', 'Torre en Cameros', 'torre en cameros', 'torre-en-cameros', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'torre en cameros torre en cameros rioja la la rioja 261531 l01261531'),
('L01261510', '261510', 'Torrecilla en Cameros', 'torrecilla en cameros', 'torrecilla-en-cameros', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'torrecilla en cameros torrecilla en cameros rioja la la rioja 261510 l01261510'),
('L01261525', '261525', 'Torrecilla sobre Alesanco', 'torrecilla sobre alesanco', 'torrecilla-sobre-alesanco', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'torrecilla sobre alesanco torrecilla sobre alesanco rioja la la rioja 261525 l01261525'),
('L01261546', '261546', 'Torremontalbo', 'torremontalbo', 'torremontalbo', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'torremontalbo torremontalbo rioja la la rioja 261546 l01261546'),
('L01261559', '261559', 'Treviana', 'treviana', 'treviana', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'treviana treviana rioja la la rioja 261559 l01261559'),
('L01261578', '261578', 'Tricio', 'tricio', 'tricio', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'tricio tricio rioja la la rioja 261578 l01261578'),
('L01261584', '261584', 'Tudelilla', 'tudelilla', 'tudelilla', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'tudelilla tudelilla rioja la la rioja 261584 l01261584'),
('L01261601', '261601', 'Uruñuela', 'urunuela', 'urunuela', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'urunuela urunuela rioja la la rioja 261601 l01261601'),
('L01261618', '261618', 'Valdemadera', 'valdemadera', 'valdemadera', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'valdemadera valdemadera rioja la la rioja 261618 l01261618'),
('L01261623', '261623', 'Valgañón', 'valganon', 'valganon', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'valganon valganon rioja la la rioja 261623 l01261623'),
('L01261639', '261639', 'Ventosa', 'ventosa', 'ventosa', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'ventosa ventosa rioja la la rioja 261639 l01261639'),
('L01261644', '261644', 'Ventrosa', 'ventrosa', 'ventrosa', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'ventrosa ventrosa rioja la la rioja 261644 l01261644'),
('L01261657', '261657', 'Viguera', 'viguera', 'viguera', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'viguera viguera rioja la la rioja 261657 l01261657'),
('L01261660', '261660', 'Villalba de Rioja', 'villalba de rioja', 'villalba-de-rioja', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'villalba de rioja villalba de rioja rioja la la rioja 261660 l01261660'),
('L01261676', '261676', 'Villalobar de Rioja', 'villalobar de rioja', 'villalobar-de-rioja', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'villalobar de rioja villalobar de rioja rioja la la rioja 261676 l01261676'),
('L01261682', '261682', 'Villamediana de Iregua', 'villamediana de iregua', 'villamediana-de-iregua', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'villamediana de iregua villamediana de iregua rioja la la rioja 261682 l01261682'),
('L01261695', '261695', 'Villanueva de Cameros', 'villanueva de cameros', 'villanueva-de-cameros', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'villanueva de cameros villanueva de cameros rioja la la rioja 261695 l01261695'),
('L01261709', '261709', 'Villar de Arnedo, El', 'villar de arnedo, el', 'villar-de-arnedo-el', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'villar de arnedo el villar de arnedo el rioja la la rioja 261709 l01261709'),
('L01261716', '261716', 'Villar de Torre', 'villar de torre', 'villar-de-torre', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'villar de torre villar de torre rioja la la rioja 261716 l01261716'),
('L01261721', '261721', 'Villarejo', 'villarejo', 'villarejo', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'villarejo villarejo rioja la la rioja 261721 l01261721'),
('L01261737', '261737', 'Villarroya', 'villarroya', 'villarroya', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'villarroya villarroya rioja la la rioja 261737 l01261737'),
('L01261742', '261742', 'Villarta-Quintana', 'villarta-quintana', 'villarta-quintana', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'villarta quintana villarta quintana rioja la la rioja 261742 l01261742'),
('L01261755', '261755', 'Villavelayo', 'villavelayo', 'villavelayo', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'villavelayo villavelayo rioja la la rioja 261755 l01261755'),
('L01261768', '261768', 'Villaverde de Rioja', 'villaverde de rioja', 'villaverde-de-rioja', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'villaverde de rioja villaverde de rioja rioja la la rioja 261768 l01261768'),
('L01261774', '261774', 'Villoslada de Cameros', 'villoslada de cameros', 'villoslada-de-cameros', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'villoslada de cameros villoslada de cameros rioja la la rioja 261774 l01261774'),
('L01261780', '261780', 'Viniegra de Abajo', 'viniegra de abajo', 'viniegra-de-abajo', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'viniegra de abajo viniegra de abajo rioja la la rioja 261780 l01261780'),
('L01261793', '261793', 'Viniegra de Arriba', 'viniegra de arriba', 'viniegra-de-arriba', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'viniegra de arriba viniegra de arriba rioja la la rioja 261793 l01261793'),
('L01261807', '261807', 'Zarratón', 'zarraton', 'zarraton', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'zarraton zarraton rioja la la rioja 261807 l01261807'),
('L01261814', '261814', 'Zarzosa', 'zarzosa', 'zarzosa', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'zarzosa zarzosa rioja la la rioja 261814 l01261814'),
('L01261835', '261835', 'Zorraquín', 'zorraquin', 'zorraquin', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'zorraquin zorraquin rioja la la rioja 261835 l01261835'),
('L01260012', '260012', 'Ábalos', 'abalos', 'abalos', '26', 'Rioja, La', '17', 'La Rioja', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'abalos abalos rioja la la rioja 260012 l01260012'),
('L01510013', '510013', 'Ceuta', 'ceuta', 'ceuta', '51', 'Ceuta', '18', 'Ciudad Autónoma de Ceuta', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'ceuta ceuta ceuta ciudad autonoma de ceuta 510013 l01510013'),
('L01520018', '520018', 'Melilla', 'melilla', 'melilla', '52', 'Melilla', '19', 'Ciudad Autónoma de Melilla', 'ES', 'DIR3 Catalogo de Localidades', 'Catalogo de Localidades.xlsx', '2026-05-12', 'melilla melilla melilla ciudad autonoma de melilla 520018 l01520018');

update public.cities as cities
set
  name = seed.name,
  slug = seed.slug,
  country_code = seed.country_code,
  province_code = seed.province_code,
  province_name = seed.province_name,
  autonomous_community_code = seed.autonomous_community_code,
  autonomous_community_name = seed.autonomous_community_name,
  municipality_code = seed.municipality_code,
  dir3_code = seed.dir3_code,
  source_name = seed.source_name,
  source_file = seed.source_file,
  name_search = seed.name_search,
  search_text = seed.search_text,
  place_type = 'municipality',
  is_active = true,
  updated_at = now()
from dir3_municipality_seed as seed
where
  cities.dir3_code = seed.dir3_code
  or (
    cities.municipality_code = seed.municipality_code
    and coalesce(cities.province_code, seed.province_code) = seed.province_code
  )
  or (
    cities.dir3_code is null
    and cities.municipality_code is null
    and cities.province_code = seed.province_code
    and cities.name_search = seed.name_search
    and not exists (
      select 1
      from public.cities as duplicate_city
      where duplicate_city.id <> cities.id
        and duplicate_city.province_code = cities.province_code
        and duplicate_city.name_search = cities.name_search
    )
  )
  or (
    cities.dir3_code is null
    and cities.municipality_code is null
    and cities.province_code is null
    and seed.province_code = '08'
    and cities.name in ('Sitges', 'Sant Pere de Ribes', 'Vilanova i la Geltrú')
    and cities.name = seed.name
  );

insert into public.cities (
  name,
  slug,
  country_code,
  province_code,
  province_name,
  autonomous_community_code,
  autonomous_community_name,
  municipality_code,
  dir3_code,
  source_name,
  source_file,
  name_search,
  search_text,
  place_type,
  is_active,
  updated_at
)
select
  seed.name,
  seed.slug,
  seed.country_code,
  seed.province_code,
  seed.province_name,
  seed.autonomous_community_code,
  seed.autonomous_community_name,
  seed.municipality_code,
  seed.dir3_code,
  seed.source_name,
  seed.source_file,
  seed.name_search,
  seed.search_text,
  'municipality',
  true,
  now()
from dir3_municipality_seed as seed
where not exists (
  select 1
  from public.cities as cities
  where cities.dir3_code = seed.dir3_code
    or cities.municipality_code = seed.municipality_code
);

do $$
declare
  current_sequence text;
  next_value bigint;
begin
  select pg_get_serial_sequence('public.cities', 'id')
  into current_sequence;

  if current_sequence is not null then
    select greatest(coalesce(max(id), 0) + 1, 1)
    into next_value
    from public.cities;

    perform setval(current_sequence::regclass, next_value, false);
  end if;
end;
$$;

commit;
